repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
  - repo: https://github.com/lietu/go-pre-commit
    rev: v1.0.0
    hooks:
      - id: go-test
      - id: go-fmt-goimports
      - id: gofumpt
      - id: golangci-lint
      - id: golint
      - id: go-mod-tidy
